apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-frontend
  name: weilplace-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-frontend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-frontend
    spec:
      containers:
        - image: erickweil/weilplace-site:kubernetes # Precisa fazer rebuild toda vez para deploy
          name: weilplace-frontend
          ports:
            - containerPort: 3000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-frontend
  name: weilplace-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    io.kompose.service: weilplace-frontend
