apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-site
  name: weilplace-site
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-site
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-site
    spec:
      containers:
        - name: weilplace-site
          image: registry.fslab.dev/erickweil/weilplace-site:latest
          imagePullSecrets:
          - name: regcred
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-site
  name: weilplace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    io.kompose.service: weilplace-site
