#include: '/templates/padrao.template.yml'
include: 'https://gitlab.fslab.dev/fslab/modelo-ci-cd/-/raw/master/templates/padrao.template.yml'

variables:
  IMG_WEILPLACE_API: registry.fslab.dev/erickweil/weilplace-api
  IMG_WEILPLACE_SITE: registry.fslab.dev/erickweil/weilplace-site
  
  KUBECTL_CONFIG: $KUBECTL_CONFIG
  API_SHARED_SECRET: $API_SHARED_SECRET
  SESSION_SECRET: $SESSION_SECRET
  OAUTH2_CLIENT_ID: $OAUTH2_CLIENT_ID

stages:
  - test
  - publish
  - deploy

test:
  extends: 
    - .on-commit-main
    - .disable-git-clone
  needs: []
  stage: test
  script:
    - echo $FUNCIONA_VARIAVEIS
    - ls -lhas
    - echo "Nome da imagem weilplace-api"
    - echo $IMG_WEILPLACE_API
    - echo "Nome da imagem weilplace-site"
    - echo $IMG_WEILPLACE_SITE
    - echo "Primeira linha da configuração kubectl"
    - head -n1 $KUBECTL_CONFIG
    - echo $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

merge-test-api:
  image: node:alpine
  extends: .on-create-merge-main
  needs: []
  stage: test
  script:
    - mv ./backend/.env.example ./backend/.env
    - cd ./backend
    - npm install
    - npm run test
#  artifacts:
#    paths:
#      - backend/node_modules

build-weilplace-api:
  extends: 
    - .on-commit-main
    - .build-docker
  needs: ["test"]
  stage: publish
  variables:
    BUILD_DIR: "./backend"
    BUILD_TAG: $IMG_WEILPLACE_API:latest
  before_script:
    - mv ./backend/.env.example ./backend/.env
    # Não tá legal, a imagem com secret? o secret deveria estar no kubernetes não?
    - echo "SESSION_SECRET=\"$SESSION_SECRET\"" >> ./backend/.env
    - echo "API_SHARED_SECRET=\"$API_SHARED_SECRET\"" >> ./backend/.env
    - echo "OAUTH2_CLIENT_ID=\"$OAUTH2_CLIENT_ID\"" >> ./backend/.env

build-weilplace-site:
  extends: 
    - .on-commit-main
    - .build-docker
  needs: ["test"]
  stage: publish
  variables:
    BUILD_DIR: "./frontend"
    BUILD_TAG: $IMG_WEILPLACE_SITE:latest
  before_script:
    - cp ./frontend/.env.production ./frontend/.env.local
    - echo "NEXT_PUBLIC_OAUTH2_CLIENT_ID=\"$OAUTH2_CLIENT_ID\"" >> ./frontend/.env.local

# https://juju.is/tutorials/using-gitlab-as-a-container-registry#7-pull-your-container
deploy-weilplace:
  extends: .on-commit-main
  needs: ["build-weilplace-site","build-weilplace-api"]
  
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    # Para ter as credenciais do kubectl
    - cat $KUBECTL_CONFIG > ~/.kube/config
    #- cat ~/.kube/config

    # Debug
    - kubectl config get-contexts
    - kubectl get node
    - kubectl get pods

    # Pedir para parar (Dependendo do que mudar na configuração não vai funciona só re-aplicar com 'rollout restart')
    - kubectl delete deployment weilplace-api || true
    - kubectl delete deployment weilplace-site || true
    - kubectl delete deployment weilplace-pixelsaver || true

    # Espera 10 segundos para ter certeza que parou tudo
    - sleep 10

    # Aplicar novamente os deployments 
    - kubectl apply -f ./backend/deployment.yaml
    - kubectl apply -f ./frontend/deployment.yaml
