services:
  weilplace-server:
    build: 
      context: ./backend
      args:
        - NODE_ENV=development
    container_name: weilplace-server
    volumes:
      - weilplace-volume-pixels:/node-app/public/pixels:ro
    environment:
      PORT: "3001"
      PATH_PICTURE: "./public/pixels/picture.png"
      LOG_ROUTES: "true"
      REDIS_ENABLED: "true"
      REDIS_URL: "redis://weilplace-redis:6379"
      PLACE_DELAY: 0
      DISABLE_FILESYSTEM: "false"
      PIXEL_SAVER_CALL: "false"
    networks:
      weilplace:
        ipv4_address: 10.5.0.2
    ports:
      - "3001:3001"
  weilplace-pixelsaver:
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    container_name: weilplace-pixelsaver
    volumes:
      - weilplace-volume-pixels:/node-app/public/pixels:rw
    entrypoint: "npm run saver"
    environment:
      API_URL: "http://weilplace-server:3001"
      PATH_PICTURE: "./public/pixels/picture.png"
      REDIS_ENABLED: "true"
      REDIS_URL: "redis://weilplace-redis:6379"
      DISABLE_FILESYSTEM: "false"
      PIXEL_SAVER_CALL: "false"
    networks:
      weilplace:
        ipv4_address: 10.5.0.3
  weilplace-frontend:
    build: 
      context: ./frontend
      args:
        - SERVERSIDE_API_URL=http://weilplace-server:3001
        # - NEXT_PUBLIC_API_URL=http://localhost:3000/backend
        # - NEXT_PUBLIC_WEBSOCKET_ENABLED=true
        # - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:3000/backend/
    container_name: weilplace-frontend
    environment:
      PORT: "3000"
      SERVERSIDE_API_URL: "http://weilplace-server:3001"
      # Especifica o caminho que irá buscar os assets, para
      # hospedar o site em um subpath /algumacoisa
      ASSET_PREFIX: ""
    networks:
      weilplace:
        ipv4_address: 10.5.0.4
    ports:
      - "3000:3000"
  weilplace-redis:
    image: redis
    container_name: weilplace-redis
    networks:
      weilplace:
        ipv4_address: 10.5.0.5
    ports:
      - "6379:6379"
  # weilplace-nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   container_name: weilplace-nginx
  #   ports:
  #     - "3000:80"
  #   networks:
  #     weilplace:
  #       ipv4_address: 10.5.0.6

volumes:
  weilplace-volume-pixels:

networks:
  weilplace:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1