# Para rodar o projeto sem construir a imagem, só mapeando direto mesmo
version: "3.3"
services:
  weilplace-server:
    build: 
      context: ./backend
      args:
        NODE_ENV: "development"
    container_name: weilplace-server
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/node-app/:rw
      - weilplace-volume-backendmodules:/node-app/node_modules:rw
      #- weilplace-volume-pixels:/node-app/public/pixels:ro
    environment:
      PORT: "3001"
      PATH_PICTURE: "./public/pixels/picture.png"
      REDIS_ENABLED: "true"
      REDIS_URL: "redis://weilplace-redis:6379"
      LOG_ROUTES: "true"
      #MAX_CHANGES_RESPONSE: 50
      #MAX_CHANGES_SIZE: 100
    entrypoint: "/bin/sh -c 'npm install && npm run devStart'"
    networks:
      - weilplace
  weilplace-pixelsaver:
    build: 
      context: ./backend
      args:
        NODE_ENV: "development"
    container_name: weilplace-pixelsaver
    volumes:
      - ./backend:/node-app/:rw
      - weilplace-volume-backendmodules:/node-app/node_modules:rw
      #- weilplace-volume-pixels:/node-app/public/pixels:rw
    environment:
      API_URL: "http://weilplace-server:3001"
      PATH_PICTURE: "./public/pixels/picture.png"
      REDIS_ENABLED: "true"
      REDIS_URL: "redis://weilplace-redis:6379"
      #MAX_CHANGES_RESPONSE: 50
      #MAX_CHANGES_SIZE: 100
    entrypoint: "/bin/sh -c 'npm install && npm run devSaver'"
    networks:
      - weilplace
  weilplace-frontend:
    build: 
      context: ./frontend
      args:
        NODE_ENV: "development"
    container_name: weilplace-frontend
    volumes:
      - ./frontend:/node-app/:rw
      - weilplace-volume-frontendmodules:/node-app/node_modules:rw
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      SERVERSIDE_API_URL: "http://weilplace-server:3001"
      NEXT_PUBLIC_API_URL: "http://127.0.0.1:3001"

      # Websockets
      NEXT_PUBLIC_WEBSOCKET_ENABLED: "true"
      NEXT_PUBLIC_WEBSOCKET_URL: "ws://127.0.0.1:3001"
      # Especifica o caminho que irá buscar os assets, para
      # hospedar o site em um subpath /algumacoisa
      ASSET_PREFIX: ""
    entrypoint: "/bin/sh -c 'npm install && npm run dev'"
    networks:
      - weilplace
  weilplace-redis:
    image: redis
    container_name: weilplace-redis
    ports:
      - "6379:6379"
    networks:
      - weilplace

volumes:
  weilplace-volume-pixels:
  weilplace-volume-backendmodules:
  weilplace-volume-frontendmodules:

networks:
  weilplace:
    driver: bridge