apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-redis
  name: weilplace-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-redis
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-redis
    spec:
      containers:
        - image: redis
          name: weilplace-redis
          resources: {}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-redis
  name: weilplace-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: weilplace-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: weilplace-volume-pixels
  name: weilplace-volume-pixels
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-server
  name: weilplace-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-server
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-server
    spec:
      containers:
        - env:
            - name: LOG_ROUTES
              value: "false"
            - name: PATH_PICTURE
              value: ./public/pixels/picture.png
            - name: PLACE_DELAY
              value: "0"
            - name: PORT
              value: "3001"
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_URL
              value: redis://weilplace-redis:6379
          image: erickweil/weilplace-api:kubernetes
          name: weilplace-server
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /node-app/public/pixels
              name: weilplace-volume-pixels
              readOnly: true
      volumes:
        - name: weilplace-volume-pixels
          persistentVolumeClaim:
            claimName: weilplace-volume-pixels
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-server
  name: weilplace-server
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30090
  selector:
    io.kompose.service: weilplace-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-pixelsaver
  name: weilplace-pixelsaver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-pixelsaver
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-pixelsaver
    spec:
      containers:
        - args:
            - service_pixelsaver.js
          env:
            - name: API_URL
              value: http://weilplace-server:3001
            - name: PATH_PICTURE
              value: ./public/pixels/picture.png
          image: erickweil/weilplace-api:kubernetes
          name: weilplace-pixelsaver
          resources: {}
          volumeMounts:
            - mountPath: /node-app/public/pixels
              name: weilplace-volume-pixels
      volumes:
        - name: weilplace-volume-pixels
          persistentVolumeClaim:
            claimName: weilplace-volume-pixels