apiVersion: v1
kind: ConfigMap
metadata:
  name: weilplace-api-env
data:
  PORT: "3001"
  LOG_ROUTES: "false"
  IMAGE_WIDTH: "1024"
  IMAGE_HEIGHT: "1024"
  PLACE_DELAY: "0"
  SAVE_HISTORY: "true"
  PATH_PICTURE: "./public/pixels/picture.png"
  REDIS_ENABLED: "true"
  WEBSOCKET_ENABLED: "true"
  REDIS_URL: "redis://weilplace-redis:6379"
  API_URL: "http://weilplace-api:80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-redis
  name: weilplace-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-redis
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-redis
    spec:
      containers:
        - image: redis
          name: weilplace-redis
          resources: {}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-redis
  name: weilplace-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: weilplace-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: weilplace-volume-pixels
  name: weilplace-volume-pixels
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-api
  name: weilplace-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-api
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-api
    spec:
      containers:
        - name: weilplace-api
          image: registry.fslab.dev/erickweil/weilplace-api:latest
          imagePullSecrets:
          - name: regcred
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: weilplace-api-env
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /node-app/public/pixels
              name: weilplace-volume-pixels
              readOnly: true
      volumes:
        - name: weilplace-volume-pixels
          persistentVolumeClaim:
            claimName: weilplace-volume-pixels
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weilplace-api
  name: weilplace-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30090
  selector:
    io.kompose.service: weilplace-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weilplace-pixelsaver
  name: weilplace-pixelsaver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weilplace-pixelsaver
  template:
    metadata:
      labels:
        io.kompose.service: weilplace-pixelsaver
    spec:
      containers:
        - name: weilplace-pixelsaver
          args:
            - service_pixelsaver.js
          image: registry.fslab.dev/erickweil/weilplace-api:latest
          imagePullSecrets:
          - name: regcred
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: weilplace-api-env
          resources: {}
          volumeMounts:
            - mountPath: /node-app/public/pixels
              name: weilplace-volume-pixels
      volumes:
        - name: weilplace-volume-pixels
          persistentVolumeClaim:
            claimName: weilplace-volume-pixels